### ISSUE TITLE
Access to the  Dataset.

### ISSUE THREAD

**Issue by zkp0113** [ghoshraghu2610/HAR_WITH_TRANSFER_AND_WRAPPER#1]
Dear sir,
I am very interested in your research , may I  access to the dataset that you used in your research?

**Comment by ghoshraghu2610** [comment]
Please find below link for dataset 
KU-HAR : https://data.mendeley.com/datasets/45f952y38r/5 
HuGaDB : https://github.com/romanchereshnev/HuGaDB
HARTH :https://github.com/ntnu-ai-lab/harth-ml-experiments
